### ISSUE TITLE
Inconsistencies with metadata as served by Matrix Service

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/hca_bundles_to_csv#9]
@calvinnhieu [commented](https://docs.google.com/a/chanzuckerberg.com/document/d/1u2OOkqnKtVKUhg-yWowuUco_P-A4p8VBx0oAai7E8aU/edit?disco=AAAACm7fznc&usp=comment_email_discussion&usp_dm=false&ts=5ca2ddc0) on planning document.

+jupp@ebi.ac.uk

A few discrepancies I came across between the matrix metadata and the project TSVs I'd like to sync on:

1. Matrix metadata includes (while project TSVs do not) `provenance.document_id` fields, previously as `donorkey` and `librarykey` and currently do not map to a field in the project TSV. Will project TSVs include these?

2. The values for organs (ontology and label) in matrix metadata is determined differently than the project level TSVs and results in a discrepancy in values.

3. Project TSVs use `library_preparation_protocol.input_nucleic_acid_molecule.text`. Do we want to use `library_preparation_protocol.input_nucleic_acid_molecule.ontology_label` to be consistent with other fields?

**Comment by hannes-ucsc** [comment]
@GPelayo Geryl could you quickly check @calvinnhieu's points above are still an issue?

**Comment by GPelayo** [comment]
@hannes-ucsc I check it out now.

**Comment by calvinnhieu** [comment]
Hey @hannes-ucsc @GPelayo,

The comment is outdated and was discussed in a separate email thread titled "Beta 2 Readiness" (@hannes-ucsc CC'd). The current state of these issues are:

_1. Matrix metadata includes (while project TSVs do not) provenance.document_id fields, previously as donorkey and librarykey and currently do not map to a field in the project TSV. Will project TSVs include these?_
I don't believe project TSVs include these fields yet. @simonjupp?

_2. The values for organs (ontology and label) in matrix metadata is determined differently than the project level TSVs and results in a discrepancy in values._
Since the project TSV generator serves metadata values as is and provides all various organ fields, whereas the Matrix Service derives a single organ according to this [algorithm](https://github.com/HumanCellAtlas/data-browser/issues/302#issuecomment-433978384), the resolution was to use [human readable field names](https://github.com/HumanCellAtlas/matrix-service/commit/3ad63a53f48b42f666df94a116111fda729125e0) in the Matrix Service over schema names.

_3. Project TSVs use library_preparation_protocol.input_nucleic_acid_molecule.text. Do we want to use library_preparation_protocol.input_nucleic_acid_molecule.ontology_label to be consistent with other fields?_
This was incorrect and a non-issue. The project TSVs do serve both fields.

**Comment by GPelayo** [comment]
@calvinnhieu To answer your first question, the project TSVs now has the provenance.document_id fields, such as `library_preparation_protocol.provenance.document_id` and `donor_organism.provenance.document_id`.

**Comment by calvinnhieu** [comment]
Great! Given that, I believe this issue can be closed.
